### PR TITLE
fix: prompt defaults

### PR DESCRIPTION
**Pull request by matq007**
- Organism supports now mouse & human as one option
- Some defaults for each prompt were moved so they are not default anymore
- In case of external resource, cookiecutter doesn't support conditional prompts yet, so alternative is not just showing the message to copy files genomics folder

### CODE REVIEW

**Review by SLundregan — APPROVED** [review]
Looks good to me

**Comment by matq007** [comment]
I realized that genome version has to also support multiple versions, so one more change.

**Review by SLundregan — COMMENTED** [review]
I just remembered that GCF are starting to map to mm39 by default if people do not ask for mm10. Perhaps we should add mm39 or make the organism version free-choice for future compatibility?

**Review by nazsalehin — APPROVED** [review]
Looks good.

**Pull request merged**
